/*
 * ==========================================
 * |          GENERATED BY SUPAZOD          |
 * ==========================================
 */

import { z } from "zod";
import * as generated from "./schemas";
export type Json = z.infer<typeof generated.jsonSchema>;
export type PublicLogsRow = z.infer<typeof generated.publicLogsRowSchema>;
export type PublicLogsInsert = z.infer<typeof generated.publicLogsInsertSchema>;
export type PublicLogsUpdate = z.infer<typeof generated.publicLogsUpdateSchema>;
export type PublicBinaryQuantizeArgs = z.infer<
  typeof generated.publicBinaryQuantizeArgsSchema
>;
export type PublicBinaryQuantizeReturns = z.infer<
  typeof generated.publicBinaryQuantizeReturnsSchema
>;
export type PublicHalfvecAvgArgs = z.infer<
  typeof generated.publicHalfvecAvgArgsSchema
>;
export type PublicHalfvecAvgReturns = z.infer<
  typeof generated.publicHalfvecAvgReturnsSchema
>;
export type PublicHalfvecOutArgs = z.infer<
  typeof generated.publicHalfvecOutArgsSchema
>;
export type PublicHalfvecOutReturns = z.infer<
  typeof generated.publicHalfvecOutReturnsSchema
>;
export type PublicHalfvecSendArgs = z.infer<
  typeof generated.publicHalfvecSendArgsSchema
>;
export type PublicHalfvecSendReturns = z.infer<
  typeof generated.publicHalfvecSendReturnsSchema
>;
export type PublicHalfvecTypmodInArgs = z.infer<
  typeof generated.publicHalfvecTypmodInArgsSchema
>;
export type PublicHalfvecTypmodInReturns = z.infer<
  typeof generated.publicHalfvecTypmodInReturnsSchema
>;
export type PublicHnswBitSupportArgs = z.infer<
  typeof generated.publicHnswBitSupportArgsSchema
>;
export type PublicHnswBitSupportReturns = z.infer<
  typeof generated.publicHnswBitSupportReturnsSchema
>;
export type PublicHnswHalfvecSupportArgs = z.infer<
  typeof generated.publicHnswHalfvecSupportArgsSchema
>;
export type PublicHnswHalfvecSupportReturns = z.infer<
  typeof generated.publicHnswHalfvecSupportReturnsSchema
>;
export type PublicHnswSparsevecSupportArgs = z.infer<
  typeof generated.publicHnswSparsevecSupportArgsSchema
>;
export type PublicHnswSparsevecSupportReturns = z.infer<
  typeof generated.publicHnswSparsevecSupportReturnsSchema
>;
export type PublicHnswhandlerArgs = z.infer<
  typeof generated.publicHnswhandlerArgsSchema
>;
export type PublicHnswhandlerReturns = z.infer<
  typeof generated.publicHnswhandlerReturnsSchema
>;
export type PublicIvfflatBitSupportArgs = z.infer<
  typeof generated.publicIvfflatBitSupportArgsSchema
>;
export type PublicIvfflatBitSupportReturns = z.infer<
  typeof generated.publicIvfflatBitSupportReturnsSchema
>;
export type PublicIvfflatHalfvecSupportArgs = z.infer<
  typeof generated.publicIvfflatHalfvecSupportArgsSchema
>;
export type PublicIvfflatHalfvecSupportReturns = z.infer<
  typeof generated.publicIvfflatHalfvecSupportReturnsSchema
>;
export type PublicIvfflathandlerArgs = z.infer<
  typeof generated.publicIvfflathandlerArgsSchema
>;
export type PublicIvfflathandlerReturns = z.infer<
  typeof generated.publicIvfflathandlerReturnsSchema
>;
export type PublicL2NormArgs = z.infer<typeof generated.publicL2NormArgsSchema>;
export type PublicL2NormReturns = z.infer<
  typeof generated.publicL2NormReturnsSchema
>;
export type PublicL2NormalizeArgs = z.infer<
  typeof generated.publicL2NormalizeArgsSchema
>;
export type PublicL2NormalizeReturns = z.infer<
  typeof generated.publicL2NormalizeReturnsSchema
>;
export type PublicSparsevecOutArgs = z.infer<
  typeof generated.publicSparsevecOutArgsSchema
>;
export type PublicSparsevecOutReturns = z.infer<
  typeof generated.publicSparsevecOutReturnsSchema
>;
export type PublicSparsevecSendArgs = z.infer<
  typeof generated.publicSparsevecSendArgsSchema
>;
export type PublicSparsevecSendReturns = z.infer<
  typeof generated.publicSparsevecSendReturnsSchema
>;
export type PublicSparsevecTypmodInArgs = z.infer<
  typeof generated.publicSparsevecTypmodInArgsSchema
>;
export type PublicSparsevecTypmodInReturns = z.infer<
  typeof generated.publicSparsevecTypmodInReturnsSchema
>;
export type PublicVectorAvgArgs = z.infer<
  typeof generated.publicVectorAvgArgsSchema
>;
export type PublicVectorAvgReturns = z.infer<
  typeof generated.publicVectorAvgReturnsSchema
>;
export type PublicVectorDimsArgs = z.infer<
  typeof generated.publicVectorDimsArgsSchema
>;
export type PublicVectorDimsReturns = z.infer<
  typeof generated.publicVectorDimsReturnsSchema
>;
export type PublicVectorNormArgs = z.infer<
  typeof generated.publicVectorNormArgsSchema
>;
export type PublicVectorNormReturns = z.infer<
  typeof generated.publicVectorNormReturnsSchema
>;
export type PublicVectorOutArgs = z.infer<
  typeof generated.publicVectorOutArgsSchema
>;
export type PublicVectorOutReturns = z.infer<
  typeof generated.publicVectorOutReturnsSchema
>;
export type PublicVectorSendArgs = z.infer<
  typeof generated.publicVectorSendArgsSchema
>;
export type PublicVectorSendReturns = z.infer<
  typeof generated.publicVectorSendReturnsSchema
>;
export type PublicVectorTypmodInArgs = z.infer<
  typeof generated.publicVectorTypmodInArgsSchema
>;
export type PublicVectorTypmodInReturns = z.infer<
  typeof generated.publicVectorTypmodInReturnsSchema
>;
