/*
 * ==========================================
 * |          GENERATED BY SUPAZOD          |
 * ==========================================
 */

import { z } from "zod";
import * as generated from "./schemas";
export type Json = z.infer<typeof generated.jsonSchema>;
export type PublicExerciserepsRow = z.infer<typeof generated.publicExerciseRepsRowSchema>;
export type PublicExerciserepsInsert = z.infer<
  typeof generated.publicExerciseRepsInsertSchema
>;
export type PublicExerciserepsUpdate = z.infer<
  typeof generated.publicExerciseRepsUpdateSchema
>;
export type PublicExerciserepsRelationships = z.infer<
  typeof generated.publicExerciseRepsRelationshipsSchema
>;
export type PublicExercisesessionsRow = z.infer<
  typeof generated.publicExerciseSessionsRowSchema
>;
export type PublicExercisesessionsInsert = z.infer<
  typeof generated.publicExerciseSessionsInsertSchema
>;
export type PublicExercisesessionsUpdate = z.infer<
  typeof generated.publicExerciseSessionsUpdateSchema
>;
export type PublicExercisesessionsRelationships = z.infer<
  typeof generated.publicExerciseSessionsRelationshipsSchema
>;
export type PublicExercisesRow = z.infer<typeof generated.publicExercisesRowSchema>;
export type PublicExercisesInsert = z.infer<typeof generated.publicExercisesInsertSchema>;
export type PublicExercisesUpdate = z.infer<typeof generated.publicExercisesUpdateSchema>;
